language: erlang
otp_release:
  - 17.5

dist: trusty
sudo: required

before_script:
  - >
    export COMMENTS_URL="https://api.github.com/repos/robnet72/test_chat_pr/issues/${TRAVIS_PULL_REQUEST}/comments"
  - export TEST_RESULT_STR="Only pull requests and pushes to master/stable are handled"
#  - >
#    if [[ "${TRAVIS_BRANCH}" != "test" && "${TRAVIS_BRANCH}" != "from-test" ]]; then
#      echo "Currently only test branches are supported, exiting..."
#      exit 0
#    fi
  - >
    if [ "${TRAVIS_EVENT_TYPE}" == "push" ] && [[ "${TRAVIS_BRANCH}" != "stable" && "${TRAVIS_BRANCH}" != "master" ]]; then
      echo "Push event will be processed only for stable and master branches, exiting..."
      exit 0
    elif [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ]; then
      echo "For branches other then stable or master only pull requests are processed, exiting..."
      exit 0
    fi

script:
  - >
    notify_github() {
      curl "${COMMENTS_URL}?access_token=${GITHUB_ACCESS_TOKEN}" -H "Content-Type: application/json" -X POST -d "{\"body\": \"Travis test result: ${1}\"}"
    }
# test if it's mergeable into master
#  - git checkout master
#  - git merge "origin/${TRAVIS_BRANCH}"
  - export TEST_RESULT_STR="FAILED"
  - ./bla.sh
  - >
    if [ $? -ne 0 ]; then
      notify_github "FAILED"
      exit 1
    fi
  - git branch
  - cat test.txt
  - export TEST_RESULT_STR="All tests passed successfully"

notifications:
  slack:
    rooms:
      - grindr:erUk5hQOSgZChjBYBBa2bbMl
    on_success: always
    on_failure: always

after_script:
  - notify_github "All tests passed successfully"
