language: erlang
otp_release:
  - 17.5

dist: trusty
sudo: required

before_script:
#  - >
#    if [[ "${TRAVIS_BRANCH}" != "test" && "${TRAVIS_BRANCH}" != "from-test" ]]; then
#      echo "Currently only test branches are supported, exiting..."
#      exit 0
#    fi
  - >
    if [ "${TRAVIS_EVENT_TYPE}" == "push" ] && [[ "${TRAVIS_BRANCH}" != "stable" && "${TRAVIS_BRANCH}" != "master" ]]; then
      echo "Push event will be processed only for stable and master branches, exiting..."
      exit 0
    elif [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ]; then
      echo "For branches other then stable or master only pull requests are processed, exiting..."
      exit 0
    fi

script:
  - echo "HELLO"
  - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
# test if it's mergeable into master
#  - git checkout master
#  - git merge "origin/${TRAVIS_BRANCH}"
  - git branch
  - cat test.txt

#notifications:
#  email:
#    on_pull_requests: true
#    recipients:
#      - robert.tibljas@grindr.com
#    on_success: always
#    on_failure: always

notifications:
  slack:
    rooms:
      - grindr:erUk5hQOSgZChjBYBBa2bbMl
    on_success: always
    on_failure: always

after_script:
  - echo "ALWAYS"
