language: erlang
otp_release:
  - 17.5

dist: trusty
sudo: required

before_script:
#  - >
#    if [[ "${TRAVIS_BRANCH}" != "test" && "${TRAVIS_BRANCH}" != "from-test" ]]; then
#      echo "Currently only test branches are supported, exiting..."
#      exit 0
#    fi
  - >
    if [ "${TRAVIS_EVENT_TYPE}" == "push" ] && [[ "${TRAVIS_BRANCH}" != "stable" && "${TRAVIS_BRANCH}" != "master" ]]; then
      echo "Push event will be processed only for stable and master branches, exiting..."
      exit 0
    elif [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ]; then
      echo "For branches other then stable or master only pull requests are processed, exiting..."
      exit 0
    fi

script:
  - echo "ALOHA"
  - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
# test if it's mergeable into master
#  - git checkout master
#  - git merge "origin/${TRAVIS_BRANCH}"
  - git branch
  - cat test.txt
  - COMMENTS_URL="https://api.github.com/repos/robnet72/test_chat_pr/comments/${TRAVIS_PULL_REQUEST}"
  - STATE="true"
  - STATE_DESC="All tests passed"
  - GITHUB_ACCESS_TOKEN="a1b2c3d4e5f6"
  - curl "$COMMENTS_URL?access_token=$GITHUB_ACCESS_TOKEN" -H 'Content-Type: application/json' -X POST -d "{\"body\": \"Travis PR test result: ($STATE) - $STATE_DESC\"}"

notifications:
  slack:
    rooms:
      - grindr:erUk5hQOSgZChjBYBBa2bbMl
    on_success: always
    on_failure: always

after_script:
  - echo "ALWAYS"
