language: erlang
otp_release:
  - 17.5

dist: trusty
sudo: required

before_script:
  - >
    COMMENTS_URL="https://api.github.com/repos/robnet72/test_chat_pr/issues/${TRAVIS_PULL_REQUEST}/comments"
  - TEST_RESULT_STR="Only pull requests and pushes to master/stable are handled"
#  - >
#    if [[ "${TRAVIS_BRANCH}" != "test" && "${TRAVIS_BRANCH}" != "from-test" ]]; then
#      echo "Currently only test branches are supported, exiting..."
#      exit 0
#    fi
  - >
    if [ "${TRAVIS_EVENT_TYPE}" == "push" ] && [[ "${TRAVIS_BRANCH}" != "stable" && "${TRAVIS_BRANCH}" != "master" ]]; then
      echo "Push event will be processed only for stable and master branches, exiting..."
      exit 0
    elif [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ]; then
      echo "For branches other then stable or master only pull requests are processed, exiting..."
      exit 0
    fi

script:
# test if it's mergeable into master
#  - git checkout master
#  - git merge "origin/${TRAVIS_BRANCH}"
  - git branch
  - cat test.txt
  - TEST_RESULT_STR="All tests passed successfully"

notifications:
  slack:
    rooms:
      - grindr:erUk5hQOSgZChjBYBBa2bbMl
    on_success: always
    on_failure: always

notifications:
  webhooks:
    urls:
      - "${COMMENTS_URL}?access_token=${GITHUB_ACCESS_TOKEN}"
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
#  - >
#    curl "${COMMENTS_URL}?access_token=${GITHUB_ACCESS_TOKEN}" -H "Content-Type: application/json" -X POST -d "{\"body\": \"Travis PR test result: ${TEST_RESULT_STR}\"}"
