language: erlang
otp_release:
  - 17.5

dist: trusty
sudo: required

#addons:
#  apt:
#    packages:
#       - libpam0g-dev
#       - libexpat1-dev
#       - oracle-java8-installer

before_script:
  - >
    if [[ "${TRAVIS_EVENT_TYPE}" == "push" ]] && [[ "${TRAVIS_BRANCH}" != "stable" || "${TRAVIS_BRANCH}" != "master" ]]; then
      echo "Push will be processed only on stable and master branches, exiting..."
      exit 0
    elif [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ]; then
      echo "For branches other then stable or master only pull requests are processed, exiting..."
      exit 0
    fi

script:
  - cat test.txt
  - echo "HELLO"
  - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
#before_script:
#  - sudo rabbitmqctl start_app
#  - sudo rabbitmq-plugins disable rabbitmq_shovel rabbitmq_mqtt eldap
#  - sudo rabbitmq-plugins enable rabbitmq_management
#  - curl http://localhost:15672/cli/rabbitmqadmin > /tmp/rabbitmqadmin && chmod +x /tmp/rabbitmqadmin
#  - sudo rabbitmqctl add_vhost grindr_test_vhost
#  - sudo rabbitmqctl set_permissions -p grindr_test_vhost guest ".*" ".*" ".*"
#script: make
#after_failure:
#  - cat `find . -name \*.log -print | tail -3`

services:
  - redis-server
  - rabbitmq

#branches:
#  only:
#    - stable
#    - master

