language: c

dist: trusty
sudo: required


before_script:
  - >
    if [ "${TRAVIS_EVENT_TYPE}" == "push" ] && [[ "${TRAVIS_BRANCH}" != "stable" && "${TRAVIS_BRANCH}" != "master" ]]; then
      echo "Push event will be processed only for stable and master branches, exiting..."
      exit 0
    elif [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ]; then
      echo "For branches other then stable or master only pull requests are processed, exiting..."
      exit 0
    fi

script:
  - >
    export GITHUB_COMMENTS_URL="https://api.github.com/repos/robnet72/test_chat_pr/issues/${TRAVIS_PULL_REQUEST}/comments?access_token=${GITHUB_ACCESS_TOKEN}"
  - >
    notify_github() {
      curl "${GITHUB_COMMENTS_URL}" -H "Content-Type: application/json" -X POST -d "{\"body\": \"Travis PR test result: ${1}\"}"
    }
  - echo "$TRAVIS_BRANCH"
  - >
    if [ $TRAVIS_TEST_RESULT -ne 0 ]; then
      notify_github "(FAILED) Cannot merge into master"
      exit $TRAVIS_TEST_RESULT
    fi
  - echo "$TRAVIS_PULL_REQUEST_BRANCH"
  - >
    if [ $TRAVIS_TEST_RESULT -ne 0 ]; then
      notify_github "(FAILED) make deps"
      exit $TRAVIS_TEST_RESULT
    fi
  - cat test.txt
  - which mix
  - mix --version
  - sudo apt-get remove --purge erlang* || true
  - sudo apt-get remove --purge elixir* || true
  - sudo apt-get autoremove
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get update
  - sudo apt-get install elixir
  - export PATH=/usr/local/bin:/usr:bin:$PATH
  - which mix
  - mix --version
  - mix local.hex --force
  - ls -la $MIX_ARCHIVES
  - echo "YES" | kiex implode || true
  - rm -rf "$HOME/.mix" "$HOME/.kiex/"
  - pwd
  - unset MIX_ARCHIVES
  - mix local.hex --force
#  - sudo apt list --installed
  - which kiex
  - printenv
  - sudo find / -iname erl 2>/dev/null
  - sudo find / -iname elixir 2>/dev/null
  - elixir --version
  - echo $PATH

notifications:
  slack:
    rooms:
      - grindr:erUk5hQOSgZChjBYBBa2bbMl
    on_success: always
    on_failure: always

after_success:
  - notify_github "(success) All checks have passed"

after_failure:
  - notify_github "(FAILED) For details check log"
